### ISSUE TITLE
Unable to use presign URL

### ISSUE THREAD

**Issue by jascsch** [anton-yurchenko/s3-pre-signed-url#16]
**Describe the bug**
The output of the presign URL does not work.

**GitHub Actions workflow**

```yaml
- name: Generate S3 PreSigned URL
  uses: anton-yurchenko/s3-pre-signed-url@v1
  id: s3
  with:
    region: eu-central-1
    access_key: ${{ secrets.AWS_ACCESS_KEY }}
    secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    bucket: ${{ inputs.bucket }}
    path: dumps/Corp-Root-CA-G2.zip
    expires_in: 300
- name: PreSigned URL
  run: echo ${{ steps.s3.outputs.url }}
```

**Input values (please complete the following information):**

- Version: `v1`
- region: `eu-central-1`
- bucket: `mbtointlogs`
- path: `dumps/Corp-Root-CA-G2.zip`
- expires_in: `300`

**Expected behavior**
the output should generate a presign URL which can be used to download the bucket file.

**Screenshots**
![image](https://github.com/anton-yurchenko/s3-pre-signed-url/assets/108456658/3f579ef1-4233-4711-8fc2-2ff2fc4d21a5)

**Additional context**
- self-hosted runner on linux EC2 instance Ubuntu 22.04 LTS
